name: Hostinger staging deploy

on:
  push:
    branches:
      - feature/deploy-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to staging
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          remote-dir: /home/u143407698/domains/kcg.org.uk/public_html/wp-content-staging
          git-ftp-args: --delete
          exclude: |
            .git*
            .github*
